spring.application.name=microservice
server.port=8089

jwt.secret=nhfc6HAxsZSzhyqZrVd7ANzR8zKLh2+u9gac7Mc3MCqcDoVZzQyXqzZYEKFXCoP9l6gkpi+VDiEZtD3eBBf4Eg==
web-endpoint.url=http://localhost:3000

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urlsPrimaryName=User Service
springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=http://localhost:8081/v3/api-docs
springdoc.swagger-ui.urls[1].name=Ticket Service
springdoc.swagger-ui.urls[1].url=http://localhost:8082/v3/api-docs
springdoc.swagger-ui.urls[2].name=Notification Service
springdoc.swagger-ui.urls[2].url=http://localhost:8080/v3/api-docs
springdoc.swagger-ui.urls[3].name=Gateway
springdoc.swagger-ui.urls[3].url=http://localhost:8089/v3/api-docs