spring.application.name=microservice
server.port=${SERVER_PORT:8081}

jwt.secret=${JWT_SECRET:$nhfc6HAxsZSzhyqZrVd7ANzR8zKLh2+u9gac7Mc3MCqcDoVZzQyXqzZYEKFXCoP9l6gkpi+VDiEZtD3eBBf4Eg==}
jwt.validity=${JWT_VALIDITY:3840000}
web-endpoint.url=${WEB_ENDPOINT_URL:http://localhost:3000,http://localhost:8089}

# MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/helpdesk_user}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:helpdesk}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:helpdesk}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect