spring:
  application:
    name: helpDesk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HelpDesk
    username: infra
    password: "infra"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  main:
    allow-circular-references: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  cache:
    type: redis
    redis:
      time-to-live: PT5M
      cache-null-values: false
      key-prefix: "app::"
  web:
    error:
      include-message: always

logging:
  level:
    org.springframework.cache.interceptor.CacheInterceptor: TRACE

server:
  forward-headers-strategy: native
  error:
    include-binding-error: always


jwt:
  validity: 3600000
  secret: RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdWUgZGUgdG9kbyBvIFVuaXZlcnNvIGUgcG9yIHF1ZSBlbGUgZXN04SBhcnJpc2NhdmVsLCBlbGUgZGVzYXBhcmljZSBpbnN0YW5lYSBzdWJzdGl0dWNvbiBwZXJmaXRvLi4u


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

web-endpoint:
  url: "http://localhost:5173"