spring:
  application:
    name: helpDesk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_IP}:3306/HelpDesk
    username: root
    password: infra
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: myuser
    password: secret
  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false
  cache:
    type: redis
    redis:
      time-to-live: PT5M
      cache-null-values: false
      key-prefix: "app::"
  web:
    error:
      include-message: always

logging:
  level:
    org.springframework.cache.interceptor.CacheInterceptor: TRACE


server:
  forward-headers-strategy: native
  error:
    include-binding-error: always

jwt:
  validity: 3600000
  secret: RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YXRhbWVudGUgcGFyYSBxdWUgc2VydmUgbyBVbml2ZXJzbyBlIHBvciBxdWUgZWxlIGVzdOEgYXF1aSwgZWxlIGRlc2FwYXJlY2Vy4SBpbnN0YW50YW5lYW1lbnRlIGUgc2Vy4SBzdWJzdGl0de1kbyBwb3IgYWxnbyBhaW5kYSBtYWlzIGVzdHJhbmhvIGUgaW5leHBsaWPhdmVsLiBFeGlzdGUgdW1hIHNlZ3VuZGEgdGVvcmlhIHF1ZSBkaXogcXVlIGlzc28gauEgYWNvbnRlY2V1Li4u

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

web-endpoint:
  url: ${WEB_URL_ENDPOINT}